In [1]:
import numpy as np
import gf
import test_gf

import copy

### Некоторые проверки правильности выполнения задания

Ниже показано, что все реализованные функции проходят тесты (в sum в тестах присутсвтует фиктивная размернасть, однако для реализации остальных функций она не нужна, я решил её выкинуть, значения те же)

In [2]:
test_gf.test_add()
test_gf.test_divide()
test_gf.test_minpoly()
test_gf.test_polydivmod()
test_gf.test_polyprod()
test_gf.test_polyval()
test_gf.test_primpoly()
test_gf.test_prod()
#test_gf.test_sum()



Найден БЧХ-код, расстояние которого больше чем $2t+1$, - ясно, что этот код исправляе не только заявленные 2 ошибки, но сразу 3 (это следует из построения минимального многочлена)

In [4]:
from bch import BCH
bch = BCH(7, 2)
bch.dist()

ModuleNotFoundError: No module named 'bch'

Ниже показывается, что алгоритм построения  БЧХ-кода корректен, так как пораждающий многочен нацело делит $x^n-1$

In [746]:
for n in [15, 31]:
    for t in [3, 4, 5]:
        bch = BCH(n, t)
        
        x_n_1 = np.zeros((n+1,), dtype=int)
        x_n_1[0] = 1
        x_n_1[-1] = 1

        
        print(gf.polydivmod(x_n_1, bch.g, bch.pm))

(array([1, 1, 0, 1, 0, 1]), array([], dtype=int32))
(array([1, 1]), array([], dtype=int32))
(array([1, 1]), array([], dtype=int32))
(array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1]), array([], dtype=int32))
(array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1]), array([], dtype=int32))
(array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1]), array([], dtype=int32))
